# Generated by Django 4.1.7 on 2023-03-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lecturer_gender_student_gender_alter_lecturer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.AddField(
            model_name='customizeduser',
            name='gender',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
