# Generated by Django 4.1.7 on 2023-03-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_adminmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='massage',
            field=models.CharField(max_length=1000),
        ),
    ]
