# Generated by Django 4.1.7 on 2023-03-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_lecturer_gender_remove_student_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_pic',
            field=models.ImageField(null=True, upload_to='stu_id_pics'),
        ),
    ]
