# Generated by Django 4.1.7 on 2023-03-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_adminmessage_massage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmessage',
            old_name='massage',
            new_name='message',
        ),
    ]
