# Generated by Django 4.1.7 on 2023-03-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0004_student_id_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='departments', to='main.department'),
        ),
    ]
