# Generated by Django 4.1.7 on 2023-03-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_massage_adminmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
