# Generated by Django 4.1.7 on 2023-04-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_lecturer_department_lecturer_departments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminMessage',
        ),
    ]
