# Generated by Django 4.1.7 on 2023-04-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstudentresponse',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
