# Generated by Django 4.1.7 on 2023-03-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignment',
            name='comment',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
