# Generated by Django 4.1.7 on 2023-03-29 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_id_pic'),
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='date_due',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 1, 32, 34, 582828)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='lecturers',
            field=models.ManyToManyField(related_name='lecturers', to='users.lecturer'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='student', to='users.student'),
        ),
    ]
