# Generated by Django 4.1.7 on 2023-05-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular'), ('question', 'Question')], default='regular', max_length=8),
        ),
    ]
