# Generated by Django 4.1.7 on 2023-03-04 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='title',
            new_name='name',
        ),
    ]
