# Generated by Django 4.1.7 on 2023-05-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_assignment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='type',
        ),
    ]
