# Generated by Django 4.1.7 on 2023-03-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_id_pic'),
        ('classrooms', '0002_assignment_date_due_alter_classroom_lecturers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='users.student'),
        ),
    ]
