# Generated by Django 4.1.7 on 2023-03-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_rename_title_classroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='subtitle_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subtitle_2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
