# Generated by Django 4.1.7 on 2023-03-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_classroom_subtitle_1_classroom_subtitle_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='header_img',
            field=models.ImageField(default='default.jpg', upload_to='class-headers'),
        ),
    ]
