# Generated by Django 4.1.7 on 2023-03-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_id_pic'),
        ('classrooms', '0003_alter_classroom_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='lecturers',
            field=models.ManyToManyField(to='users.lecturer'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='users.student'),
        ),
    ]
