# Generated by Django 4.1.7 on 2023-04-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_datemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateModel',
        ),
    ]
