# Generated by Django 4.1.7 on 2023-03-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_classroom_header_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='id',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
