# Generated by Django 4.1.7 on 2023-04-26 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_delete_datemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='date_due',
            new_name='_date_due',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='date_last_mod',
            new_name='_date_last_mod',
        ),
    ]
