# Generated by Django 4.1.7 on 2023-03-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_lecturer_department'),
        ('classrooms', '0004_alter_classroom_lecturers_alter_classroom_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, to='users.student'),
        ),
    ]
