# Generated by Django 4.1.7 on 2023-04-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_rename_date_due_assignment__date_due_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='start',
            new_name='_start',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='date_created',
            new_name='_date_created',
        ),
    ]
