# Generated by Django 4.1.7 on 2023-03-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_remove_classroom_id_alter_classroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='header_img',
            field=models.ImageField(null=True, upload_to='class_headers'),
        ),
    ]
