# Generated by Django 4.1.7 on 2023-04-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0006_rename_start_meeting__start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='start',
            new_name='_start',
        ),
    ]
