# Generated by Django 4.1.7 on 2023-03-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0006_alter_classroom_header_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='header_img',
        ),
    ]
