# Generated by Django 4.1.7 on 2023-03-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0006_alter_classroom_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
