# Generated by Django 4.1.7 on 2023-04-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0007_rename_start_quiz__start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='accepting_answers',
        ),
    ]
