# Generated by Django 4.1.7 on 2023-03-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0007_alter_classroom_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
