# Generated by Django 4.1.7 on 2023-04-26 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0008_remove_quiz_accepting_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizstudentresponse',
            old_name='date_created',
            new_name='_date_created',
        ),
    ]
