# Generated by Django 4.1.7 on 2023-03-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0009_alter_classroom_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
    ]
