# Generated by Django 4.1.7 on 2023-04-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0009_rename_date_created_quizstudentresponse__date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizstudentresponse',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
