# Generated by Django 4.1.7 on 2023-04-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0010_alter_quizstudentresponse_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('title', 'classroom')},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='type',
        ),
    ]
