# Generated by Django 4.1.7 on 2023-04-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0010_remove_classroom_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=''),
        ),
    ]
