# Generated by Django 4.1.7 on 2023-04-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0011_alter_classroom_name_alter_submission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('classroom', 'title')},
        ),
    ]
