# Generated by Django 4.1.7 on 2023-04-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0011_alter_assignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='_date_mod',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
