# Generated by Django 4.1.7 on 2023-04-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0012_meeting__date_mod'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('classroom', 'title')},
        ),
    ]
