# Generated by Django 4.1.7 on 2023-04-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0012_alter_classroom_name_alter_post_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='review_complete',
            field=models.BooleanField(default=False),
        ),
    ]
