# Generated by Django 4.1.7 on 2023-04-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0016_alter_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular'), ('question', 'Question')], default='regular', max_length=8),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_pwd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
