# Generated by Django 4.1.7 on 2023-04-07 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_lecturer_profile_pic_alter_student_id_pic'),
        ('classrooms', '0017_assignment_type_meeting_meeting_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 4, 7, 12, 13, 45))),
                ('start', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('accept_after_expired', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizStuResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.quizquestion')),
            ],
        ),
    ]
