# Generated by Django 4.1.7 on 2023-04-07 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0018_quiz_quizquestion_quizsturesponse_quizquestionanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('question', models.TextField()),
                ('answer_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 21, 52, 49, 773451)),
        ),
    ]
