# Generated by Django 4.1.7 on 2023-04-07 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0020_rename_time_start_meeting_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 22, 38, 51, 118985)),
        ),
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('classroom', 'topic')},
        ),
    ]
