# Generated by Django 4.1.7 on 2023-04-07 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0021_alter_quiz_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 23, 16, 51, 725880)),
        ),
    ]
